lang: en-US
title: Samuel Dotson
email: samgdotson@gmail.com
description: Sam Dotson's Personal Website. Opinions his own.
baseurl: # the optional subpath of your site, e.g. "/blog"
url: samgdotson.github.io
author:
  name: Samuel Dotson
  twitter: samgdotson
  picture: /assets/images/dotsons.png
twitter_username: samgdotson
github_username: samgdotson
logo: # path of site logo, e.g. "/assets/images/logo.png"
search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
# remote_theme: jekyll-theme-basically-basic
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _guides
  - scope:
      path: "_guides"
      type: guides
    values:
      layout: post
      read_time: true
